### ISSUE TITLE
Add Note field for ASA Genesis

### ISSUE THREAD

**Issue by garrett-vorce** [garrett-vorce/GenerAtor#1]
https://www.reddit.com/r/AlgorandOfficial/comments/n4gyin/introducing_generator_an_open_source_tool_to/gwwimy5?utm_source=share&utm_medium=web2x&context=3

**Comment by bluesuedesw** [comment]
Great project, will be trying this out soon. Note field and supporting the different formats would be a helpful add. I've seen a few NFT's where the image URL is stored in a json array in the note field.

Just looking at the screenshots, can you also specify the number of decimal places?

**Comment by garrett-vorce** [comment]
@bluesuedesw Cheers! I've pushed the Note field to master, will look into the decimals next!

Yep, I've seen most Note fields contains a JSON object with multiple properties.
